### ISSUE TITLE
I can not import 'deform_conv_cuda'

### ISSUE THREAD

**Issue by hex-xi** [Yanan-Wang-cs/ClonedPerson#7]
### from .. import deform_conv_cuda ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' 

Hi! I have the same problem with: https://github.com/open-mmlab/mmdetection/issues/413;
But I still don't know how to solve this problem.
In your project , there exist a folder named mmdet(ClonedPerson\pipeline\1Pedestron\mmdet), 
Do I need to recompile?And which version of mmdection to download and install? Or how to solve this problem? 

您好，我遇到了这个问题，在mmdection的issues中也有人遇到，但是我还是不太清楚怎么去解决它？

好像是需要重新编译？（听说旧版本需要使用./compile.sh,或者新版本直接执行python setup.py develop）
但我看这里好像调用的是项目中自带的这个mmdet文件夹中的代码，也并没有找到compile.sh或者setup.py这两个文件，我去下载了mmdetection最新的版本，试着运行，但发现和其他环境不匹配，不清楚您用的是哪个版本的mmdection？
或者我应该怎么解决这个问题呢？

Here are the traceback details:
```
(clonedperson_1pede) D:\2_Work\experiment\ClonedPerson\pipeline\1Pedestron>sh demo.sh && cd ..
Traceback (most recent call last):
  File "tools/demo.py", line 16, in <module>
    from mmdet.apis import inference_detector, init_detector, show_result
  File "D:\2_Work\experiment\ClonedPerson\pipeline\1Pedestron\tools\..\mmdet\apis\__init__.py", line 2, in <module>
    from .train import train_detector
  File "D:\2_Work\experiment\ClonedPerson\pipeline\1Pedestron\tools\..\mmdet\apis\train.py", line 7, in <module>
    from mmdet.core.my_mmcv.runner.mean_teacher_runner import Mean_teacher_Runner as Runner
  File "D:\2_Work\experiment\ClonedPerson\pipeline\1Pedestron\tools\..\mmdet\core\__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "D:\2_Work\experiment\ClonedPerson\pipeline\1Pedestron\tools\..\mmdet\core\post_processing\__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "D:\2_Work\experiment\ClonedPerson\pipeline\1Pedestron\tools\..\mmdet\core\post_processing\bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "D:\2_Work\experiment\ClonedPerson\pipeline\1Pedestron\tools\..\mmdet\ops\__init__.py", line 1, in <module>
    from .dcn import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "D:\2_Work\experiment\ClonedPerson\pipeline\1Pedestron\tools\..\mmdet\ops\dcn\__init__.py", line 1, in <module>
    from .functions.deform_conv import deform_conv, modulated_deform_conv
  File "D:\2_Work\experiment\ClonedPerson\pipeline\1Pedestron\tools\..\mmdet\ops\dcn\functions\deform_conv.py", line 5, in <module>
    from .. import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' (D:\2_Work\experiment\ClonedPerson\pipeline\1Pedestron\tools\..\mmdet\ops\dcn\__init__.py)
```

**Comment by ShengcaiLiao** [comment]
Hi, thank you for the interest. For the first step, pedestrian detection, please refer to the project [Pedestron](https://github.com/hasanirtiza/Pedestron). We follow the [installation instructions](https://github.com/hasanirtiza/Pedestron#installation) there, specifically https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md. You can also find a setup.py in that project. If you have further trouble, please check issues in that project, or post your own issues there. Dr. Irtiza Hasan will be happy to answer you.

**Comment by hex-xi** [comment]
> Hi, thank you for the interest. For the first step, pedestrian detection, please refer to the project [Pedestron](https://github.com/hasanirtiza/Pedestron). We follow the [installation instructions](https://github.com/hasanirtiza/Pedestron#installation) there, specifically https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md. You can also find a setup.py in that project. If you have further trouble, please check issues in that project, or post your own issues there. Dr. Irtiza Hasan will be happy to answer you.

Thank you very much! It helps me. I will have a try!
